import { Provider } from 'react-redux'
import './globals.css'
import type { Metadata } from 'next'
import { store } from './store/page'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>

        {children}
        </Provider>
        </body>
    </html>
  )
}
